server:
  port: 8080

spring:
  redis:
    host: localhost
    port: 17380
    password: ''
    timeout: 3000

  datasource:
    username: root
    password: rootpass
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/testdb?useSSL=false&allowPublicKeyRetrieval=true&useTimezone=true&serverTimezone=Asia/Seoul
    # hikari:

  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  main:
    allow-bean-definition-overriding: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    url: /swagger-ui.html

logging:
  level:
    com.github.ryebook: INFO
    org.springframework.statemachine: DEBUG
    # org.hibernate.type.descriptor.sql: TRACE

custom-config:
  init-data: true