server:
  port: 8080

spring:
  datasource:
    username: root
    password: rootpass
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/testdb?useSSL=false&allowPublicKeyRetrieval=true&useTimezone=true&serverTimezone=Asia/Seoul
    # hikari:

  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  main:
    allow-bean-definition-overriding: true

logging:
  level:
    com.github.ryebook: INFO
    org.springframework.statemachine: DEBUG
    # org.hibernate.type.descriptor.sql: TRACE

custom-config:
  init-data: false