### GET products (book)
GET {{host}}/products/book
Accept: application/json

### GET products with page(book)
GET {{host}}/products/book?page=0&size=3
Accept: application/json

### PATCH products status
PATCH {{host}}/products/status
Content-Type: application/json

{
  "id": 2,
  "status": "IN_STOCK"
}