### GET products (book)
GET {{host}}/products?type=book
Accept: application/json

### GET products with page(book)
GET {{host}}/products?type=book&page=0&size=3
Accept: application/json

### GET products by id
GET {{host}}/products/30
Accept: application/json

### PATCH products status
PATCH {{host}}/products/status
Content-Type: application/json

{
  "id": 3,
  "status": "IN_STOCK"
}